### ISSUE TITLE
Support for json

### ISSUE THREAD

**Issue by serhiipalash** [vihanb/babel-plugin-wildcard#17]
Hi!
You have a great package! Thanks!

Can you add support for .json files? We need it to load all available translations at once from this filestructure
```
translations/
   en.json
   de.json
   ...
```

**Comment by vihanb** [comment]
You should be able to modify the [`exts`](https://github.com/vihanb/babel-plugin-wildcard#exts) property and add `"json"` to it to be able to load json files. Does that not work?

**Comment by serhiipalash** [comment]
All works.
Sorry, it was some bug with React Native packages cache.
Can you update README with `json` extension in examples?
