### ISSUE TITLE
Pascal Case is used for file names

### ISSUE THREAD

**Issue by serhiipalash** [vihanb/babel-plugin-wildcard#18]
You are currently using Pascal Case as default for file names, not Camel Case. Can you change this?

With Camel Case file name like this `my-test-file.js` should be `myTestFile`, but get `MyTestFile`.

You can use `humps` library for file names conversion https://www.npmjs.com/package/humps

Also you can update api with something like this if you want

```
{
    "plugins": [
        ["wildcard", {
           "camelizeNames": true
        }]
    ]
}

{
    "plugins": [
        ["wildcard", {
           "pascalizeNames": true
        }]
    ]
}
```

**Comment by celicoo** [comment]
I also observed that. Please fix it? :D

**Comment by vihanb** [comment]
Did not originally think of this. Will add a camelcase/pascalcase option in config for this...

**Comment by celicoo** [comment]
@vihanb you are awesome <3.

**Comment by vihanb** [comment]
just added this option: https://github.com/vihanb/babel-plugin-wildcard#usecamelcase let me know if you encounter any issues with it
