### ISSUE TITLE
noModifyCase not working

### ISSUE THREAD

**Issue by paulm17** [vihanb/babel-plugin-wildcard#25]
My config:

	{
	  "presets": ["env"],
	  "plugins": [
	    "jsx-event-modifiers",
	    "transform-vue-jsx",
	    ["wildcard", {
	      'noModifyCase': true,
	      "exts": ["js", "es6", "es", "jsx", "javascript", "vue"]
	    }]
	  ]
	}

I have a filename sec_1_column.jsx, which still becomes Sec1Column.

**Comment by vihanb** [comment]
This is odd... are you using latest version of plugin?

**Comment by paulm17** [comment]
> Use double quotes insteead of single quotes

Doing that change resolved it for me.  You should update the readme, as the examples as in single quotes.

Many thanks for your help.
