### ISSUE TITLE
Ability to filter files

### ISSUE THREAD

**Issue by corradio** [vihanb/babel-plugin-wildcard#28]
I'm trying to import a list of images dynamically in react-native.
Somes images have higher resolutions, so I would have img1.png, img1@2x.png etc..
I only want to import files in a folder that do not have the "@" character in their name.
Would it be possible to have an exclusion/filter option?

Thanks!

**Comment by vihanb** [comment]
this does not exist at the moment. there are plans in the future to add something like this but not yet
