### ISSUE TITLE
Will this work in a Typescript project?

### ISSUE THREAD

**Issue by GollyJer** [vihanb/babel-plugin-wildcard#36]
I'm using Expo with a Typescript (and Babel) project and getting a similar error as https://github.com/vihanb/babel-plugin-wildcard/issues/26.

![image](https://user-images.githubusercontent.com/689204/62891473-ace44e00-bcfa-11e9-91e4-a1c8a48dd65f.png)

Am I trying something that isn't expected to work?

Thanks.

**Comment by yunusyuksel** [comment]
I have same problem. will this work with typescript ?
